### ISSUE TITLE
if文の使い過ぎ

### ISSUE THREAD

**Issue by c0a21131** [C0A21119/ProjExD#10]
https://github.com/C0A21119/ProjExD/blob/1f3b3598094ebbd5cc997ddd0f5a45cff7e510a0/ex04/dodge_bomb.py#L75
if文が多いのでリストや辞書をfor文で回せば短くできるのではないか。

**Comment by C0A21119** [comment]
意見ありがとうございます。
指摘いただいた箇所は技術不足により変更することができませんでした。
