### ISSUE TITLE
変更すべき点

### ISSUE THREAD

**Issue by C0A21113** [C0A21119/ProjExD#11]
https://github.com/C0A21119/ProjExD/blob/1f3b3598094ebbd5cc997ddd0f5a45cff7e510a0/ex04/dodge_bomb.py#L5
・無駄な空白が多い
・if文をfor文でまとめたらすっきりすると思う

**Comment by C0A21119** [comment]
空白だった箇所を少なくしました。
if文とfor文は技術不足により変更できませんでした。
