### ISSUE TITLE
余分な改行

### ISSUE THREAD

**Issue by C0A21113** [C0A21119/ProjExD#3]
https://github.com/C0A21119/ProjExD/blob/88c481d9ec2969b9ed0e91aec1400a93df467c92/ex01/alphabet.py#L52

**Comment by C0A21119** [comment]
修正します

**Comment by C0A21119** [comment]
修正しました

**Comment by C0A21119** [comment]
修正しました

**Comment by C0A21119** [comment]
ありがとうございます。修正しました。

**Comment by C0A21119** [comment]
ありがとうございます。修正しました。

**Comment by C0A21119** [comment]
改善しました
