### ISSUE TITLE
変更すべき点

### ISSUE THREAD

**Issue by C0A21113** [C0A21119/ProjExD#4]
https://github.com/C0A21119/ProjExD/blob/9c6248046d1a0e7f45faa8d8c7cd0ee49d4cce0a/ex02/calc.py#L34
・余分改行が多い。
・追加するボタンを細かく分けた方がいいと思う。
・もっとコメントアウトを使ってコードの説明をした方がよい。

**Comment by C0A21119** [comment]
ご指摘ありがとうございます。
コメントアウトでより分かりやすいコードにすべく改善いたしました。
余分改行は書いているコードをより見やすくするために開けています。
追加するボタンは一つにまとめることで演算のボタンについての説明だとわかりやすくするためにまとめています。

**Comment by C0A21119** [comment]
ご指摘ありがとうございます。
コメントアウトでより分かりやすいコードにすべく改善いたしました。
余分改行は書いているコードをより見やすくするために開けています。
追加するボタンは一つにまとめることで演算のボタンについての説明だとわかりやすくするためにまとめています。
