### ISSUE TITLE
文字の色の指定

### ISSUE THREAD

**Issue by c0a21131** [C0A21119/ProjExD#5]
https://github.com/C0A21119/ProjExD/blob/9c6248046d1a0e7f45faa8d8c7cd0ee49d4cce0a/ex02/calc.py#L38
文字の色を指定するのはいいが、カラーコードのままでは何の色か見ただけでは分からない。READMEを読むと赤色とのことなのでredなど文字列で指定した方が分かり易くなると思う。

**Comment by C0A21119** [comment]
ご指摘ありがとうございます。
他のメンバーの指摘を受け、コメントアウトで色の説明を追加しました。
