### ISSUE TITLE
リストや辞書を使ってはどうか？

### ISSUE THREAD

**Issue by c0a21131** [C0A21119/ProjExD#7]
https://github.com/C0A21119/ProjExD/blob/e8762f971cc6c579690349c4c161f22999d56c3e/ex03/maze.py#L15
if文が長すぎるので、リストや辞書を使ってfor文で回せば、短くできるのではないか？

**Comment by C0A21119** [comment]
ご指摘ありがとうございます。リストによる改善を試みましたが、技術不足により規定時間までに完了することができませんでした。
